name = "registryLH"
repo = "https://github.com/hendri54/registryLH"
uuid = "af402640-c98e-11e9-15bb-1160434e7d3f"

[packages]
430be53e-b6e1-11e9-3835-cd004dc5e9d7 = { name = "TestPkgLH", path = "T/TestPkgLH" }
