name = "registryLH"
repo = "https://github.com/hendri54/registryLH"
uuid = "af402640-c98e-11e9-15bb-1160434e7d3f"

[packages]
4089ccbe-b1dc-5f86-a141-4606b18b4241 = { name = "ModelParams", path = "M/ModelParams" }
430be53e-b6e1-11e9-3835-cd004dc5e9d7 = { name = "TestPkgLH", path = "T/TestPkgLH" }
4e2d2e59-2624-5a4c-88c1-3d17c23cb908 = { name = "TestPkg2LH", path = "T/TestPkg2LH" }
6b9ba4b8-a244-52b4-a4eb-1047c71ea0f4 = { name = "UtilityFunctionsLH", path = "U/UtilityFunctionsLH" }
e3939c25-9e30-5b59-80eb-f399ae42cd76 = { name = "EconLH", path = "E/EconLH" }
