name = "registryLH"
uuid = "af402640-c98e-11e9-15bb-1160434e7d3f"
repo = "https://github.com/hendri54/registryLH"

[packages]
10801879-faf9-5fee-b4da-d4f48ef6194b = { name = "StructLH", path = "S/StructLH" }
154532ee-98b9-4eab-88d3-567e736435ea = { name = "CasesLH", path = "C/CasesLH" }
22901f0c-de03-487b-854c-cad37ed05a00 = { name = "CollegeEntry", path = "C/CollegeEntry" }
22e5d595-ed39-402f-9fe9-dc630efecdfd = { name = "ValueHistoriesLH", path = "V/ValueHistoriesLH" }
298b45c6-23f3-4de3-ba2c-df38223c59b0 = { name = "DeviationsLH", path = "D/DeviationsLH" }
2a03911c-38cb-4991-90cf-b19c323ec85f = { name = "CollegeStratWorker", path = "C/CollegeStratWorker" }
32a31e0c-6007-4c9d-b9d4-39ee3e8faef4 = { name = "CollegeStratMakie", path = "C/CollegeStratMakie" }
3b0e1a96-b255-4d83-a0e1-e023bc9c9868 = { name = "PlotsLH", path = "P/PlotsLH" }
3f1e771f-3101-4d3b-986b-cbece13f4079 = { name = "CollegeStratPlots", path = "C/CollegeStratPlots" }
4089ccbe-b1dc-5f86-a141-4606b18b4241 = { name = "ModelParams", path = "M/ModelParams" }
41cbb5d9-4a7a-4d38-8546-f9486737fd3b = { name = "ModelObjectsLH", path = "M/ModelObjectsLH" }
430be53e-b6e1-11e9-3835-cd004dc5e9d7 = { name = "TestPkgLH", path = "T/TestPkgLH" }
43a91d11-2366-4444-9ac6-7eb6ace4fe3c = { name = "EndowmentsLH", path = "E/EndowmentsLH" }
49508c3c-8e27-40b4-9cd6-56e82c4a13dd = { name = "DistributionsLH", path = "D/DistributionsLH" }
4e2d2e59-2624-5a4c-88c1-3d17c23cb908 = { name = "TestPkg2LH", path = "T/TestPkg2LH" }
54f0e08d-2c1f-4f05-829a-0c9e5bebf979 = { name = "CollegeStratCollege", path = "C/CollegeStratCollege" }
5ba6fdca-9616-4e1b-a942-77ddac530f53 = { name = "LatexLH", path = "L/LatexLH" }
69233b93-b644-4f5d-9b2e-8880c8b19068 = { name = "FilesLH", path = "F/FilesLH" }
6b9ba4b8-a244-52b4-a4eb-1047c71ea0f4 = { name = "UtilityFunctionsLH", path = "U/UtilityFunctionsLH" }
7279015e-32d5-4a9c-a3a2-56f8f226bc2c = { name = "CollegeStratData", path = "C/CollegeStratData" }
72fbd86f-1f1b-5c28-94df-d0426893c88f = { name = "EconometricsLH", path = "E/EconometricsLH" }
96c8dc4a-d23f-53b2-b478-aad5d5ab80bd = { name = "CommonLH", path = "C/CommonLH" }
bddd1445-09e8-4f50-b5c6-f025e4379dde = { name = "DataCollegeStrat", path = "D/DataCollegeStrat" }
bfa38a7c-6709-4380-90e8-18b172effef4 = { name = "CollegeStratBase", path = "C/CollegeStratBase" }
d55768a2-e002-4631-a775-946d13a333f5 = { name = "PenaltiesLH", path = "P/PenaltiesLH" }
d599ba40-5627-4e4f-b033-e40cc74d6877 = { name = "ModelStatisticsLH", path = "M/ModelStatisticsLH" }
e3939c25-9e30-5b59-80eb-f399ae42cd76 = { name = "EconLH", path = "E/EconLH" }
f9770d44-d9d3-4282-8d90-ec50d637f0bd = { name = "ToggledLH", path = "T/ToggledLH" }
